### PR TITLE
Bug fixes (GUI settings on unix, find peaks/maxima of time series)

### LINKED ISSUE #106: Bug when selecting peak from time series
Hi,
When selecting peaks (global maxima) array returned contains the first position as zero.
image

I have added the specific time series that returns this results.
Its strange because I have other time series for the same variable that were generated by other seed and this bug won't come up.
[example peaks.csv](https://github.com/dnvgl/qats/files/11029358/example.peaks.csv)

### LINKED ISSUE #108: Error report when using GUI on linux
**Describe the bug**
When running the GUI on linux it works fine initially, but when exiting the GUI you get an error where it is trying to locate the qats.settings from "var/lib/qats.settings". I expect this is to update any settings changed. Possibly it is just missing a / in front, but when running it on a large computer where many people have access it might not be the best to have a global path to update

**To Reproduce**
1. Install a fresh conda environment with python 3.9 on a linux xomputer (
2. Install qats + PyQT5
3. Open GUI with qats app
4. Close GUI to get error

**Expected behavior**
No error shown

**Screenshots**
Error screenshot
image

Error text:
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/applications/conda/envs/qats_env/lib/python3.9/site-packages/qats/app/exceptions.py", line 37, in handle_exception
    log_file = os.path.join(os.getenv("APPDATA"), "QATS.launch.pyw.log")
  File "/home/applications/conda/envs/qats_env/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Original exception was:
Traceback (most recent call last):
  File "/home/applications/conda/envs/qats_env/lib/python3.9/site-packages/qats/app/gui.py", line 528, in closeEvent
    self.save_settings()
  File "/home/applications/conda/envs/qats_env/lib/python3.9/site-packages/qats/app/gui.py", line 1179, in save_settings
    with open(self.settings_file, "w") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'var/lib/qats.settings'
``` 

**Desktop (please complete the following information):**
 - OS: Rocky Linux
 - Version: 8.6 (Green Obsidian)

### PR DESCRIPTION
**Pull request by eneelo**
## Summary 

- On unix, GUI settings are fetched from/stored to `~/.config/qats.settings`. 
  Fixes #108.
- `qats.signal.find_maxima()` updated:
   * Consistant handling of half-cycles at beginning/end of time series and avoid that end-point is included. 
     Fixes #106.
   * Parameter `up` is deprecated (had no impact on output with the updated procedure). 
- testing: added a test for `qats.signal.find_maxima()` that would have caught issue #106.

## GUI settings file on unix systems

When GUI is used on unix systems, settings are now fetched from/stored to `~/.config/qats.settings`. This choice of this location is based on [this stackexchange thread](https://unix.stackexchange.com/q/732751). See issue #108.

## qats.signal.find_maxima()

The algorithm for `qats.signal.find_maxima()` has been adjusted/improved. The main change is wrt. identification of **global** maxima (`find_maxima(x, local=False)`, the default) at the beginning and end of the time series. In some cases, the _previous code_:

- included the last point of the time series as a global maxima, or
- included a maximum with value 0 because it estimated that there was one more peak that those actually identified (ref. issue #106). 

These problems arose because the first and last index in time series were always added, to avoid loosing relevant peaks at the beginning/end of the time series.

This behavior is adjusted in the revised code: when extracting global maxima (``local=False``, the default), positive half-cycles at the beginning or end of the time series are included. For example, if there is a mean-level up-crossing before the first down-crossing, the maximum value between these crossings is included. Similarly, if there is a down-crossing after the last up-crossing, the maximum value between these crossings is included. In practice, this implies that ``up=True`` and ``up=False`` will yield the same maxima arrays, hence, the `up` parameter may be deprecated. 

Examples of the previous (undesired) behavior as well as the adjusted one are shown below.

### Examples of previous (undesired) behavior of find_maxima(local=False)

**Example 1:** Array of maxima fictitiously includes 0 due to  mean-level crossing between last two points in time series. 
Time series used is from _"examples peaks.csv"_, included in the bug report of issue #106.

 

**Example 2:** Last point of time series is included as a global maximum but shouldn't have.
Time series used is _"ZG"_ of _"simo_trans.ts"_ (found in [data](https://github.com/dnvgl/qats/tree/master/data) folder).

### Examples of new behavior of find_maxima(local=False)

**Example 1**: Only actual global maxima are now returned. Same time series as in example 1 above.

 

**Example 2**: End point is not included. Same time series as in example 2 above.

 

**Example 3**: Treatment of half-cycles at beginning/end of time series. Note that the same maxima are obtained regardless of whether ``up=True`` (maxima between up-crossings) or ``up=False`` (maxima between down-crossings) is specified (this was tested before parameter `up` was deprecated in commit [802057e](https://github.com/dnvgl/qats/commit/802057ea51026fb37a1d1075ab206880da696c9b)).
This time series is generated by multiplying _"ZG"_ of example 2 by -1.

### CODE REVIEW

**Comment by eneelo** [comment]
@tovop 
Please have a look at the adjusted code/algorithm for `qats.signal.find_maxima()` and see if you agree. 
I don't recall the motivation for originally distinguishing between identifying global maxima between up- vs. down-crossings, but find that including (positive) half-cycles at beginning/end of time series is a sound way of solving the start/end challenges of importance for time series with few maxima (e.g., due to LF oscillations). In practice, this adjusted treatment of start/end should result in the same maxima array regardless of whether one looks between up- or down-crossings.

Therefore, if you agree with the adjusted approach, I suggest that we deprecate the `up` parameter and simplify the code further (one less level of complexity in the code).

**Comment by tovop** [comment]
First and most important, I agree with the improvements and suggestion. No important functionality will be lost. Go ahead🏎️

Secondly, I recall why we distinguished between up and down crossings. I worked with analysis of wave elevation series and specifically skewed waves. Then I needed to check differences in period between up and down crossings. And that algorithm for finding max/min was built on top of that. Unnecessary and not very useful😅

**Comment by eneelo** [comment]
Ah, that makes sense. Then I will deprecate the parameter `up`, adjust and clean up the code before marking PR as ready for review.

**Comment by eneelo** [comment]
@tovop Ready for review at your convenience. Only change since last discussion in May is that `qats.signal.find_maxima(up=False)` will generate a `DeprecationWarning` and has no effect on output + I have added a test that would have caught issue #106.

**Review by tovop — APPROVED** [review]
Sound evaluations and improvement of the code. Well documented and tested.

I have actually used this part of the code a lot lately and seen several examples like the ones documented here. So about time we fixed it.

**Pull request merged**
