### PR TITLE
Sphinx documentation makeover using 'sphinx_rtd_theme'

### LINKED ISSUE #102: Sphinx documentation/API: sidebar too long (includes function, methods, properties)
**Describe the bug**
The sidebar in the API section of the Sphinx documentation is way too long, due to inclusion of functions, class properties and methods, etc. See examples in screenshots below.

**To Reproduce**
1. Update development environment according to latest version of `requirements.txt`.
2. Build Sphinx documentation: `sphinx-build -a -E -b html docs\source docs\_build`.
3. Open docs/_build/index.html in a browser, navigate to e.g. "API > qats.TimeSeries".

Issue was identified when built using Python 3.8, but is not believed to be related to Python version.

**Expected behavior**
More compact sidebar with only main heading (see last screenshot).
Alternatively, the possibility to collapse the sidebar details at desired level.

**Possible solutions**
Various adjustments of `docs/source/conf.py` have been tested without success.

Possible solutions include:
1. Change the Sphinx documentation theme to e.g. `sphinx_rtd_theme` (with associated adjustments to `conf.py`, etc.). For a good example/reference on how it could be solved and how the Sphinx documentation could then look, see [pyEMMA documentation](http://www.emma-project.org/latest/api/index.html) and the associated [conf.py](https://github.com/markovmodel/PyEMMA/blob/devel/doc/source/conf.py).

2. Use the [Furo theme](https://pradyunsg.me/furo/): "A clean customisable Sphinx documentation theme". This theme is used for, e.g.,  the [Twine documentation](https://twine.readthedocs.io/en/stable/). This theme looks like a minimalistic but highly functional alternative.

**Screenshots illustrating issue of too many levels in sidebar**

image

image

**Screenshot illustrating desired level in sidebar (taken from previous documentation for version 4.10.0)**

image

### PR DESCRIPTION
**Pull request by eneelo**
## Description 

Sphinx documentation makeover.

- [x] Implement [sphinx_rtd_theme](https://sphinx-rtd-theme.readthedocs.io/en/stable/index.html) 
- [x] Adjust `conf.py`
- [x] Update `requirements.txt`
- [x] Check out the [Furo theme](https://pradyunsg.me/furo/) as an alternative ([link to Furo on pypi](https://pypi.org/project/furo/)). See [this example of associated conf.py](https://github.com/pradyunsg/furo/blob/main/docs/conf.py). This minimalistic theme is used by e.g., [Twine](https://twine.readthedocs.io/en/stable/index.html), [Pip](https://pip.pypa.io/en/stable/) and [urllib3](https://urllib3.readthedocs.io/en/stable/).
- [x] Choose theme: `sphinx_rtd_theme` vs. `furo`. See screenshots below.
    - Selected: Furo
- [x] [if furo is selected] Update `requirements.txt` (add `furo`, remove `sphinx_rtd_theme`)

This PR fixes #102.

## Screenshots of html documentation using sphinx_rtd_theme

image

image

image

## Screenshots of html documentation using furo

_Note: The dark mode is available via the button on upper right in the generated html docs._

image

image

image

### CODE REVIEW

**Comment by eneelo** [comment]
@tovop At your convenience, have a look at the screenshots and let me know what you think of the makeover.

**Comment by tovop** [comment]
I like that one better than the old. I will spin it up tomorrow morning and look more closely🤓

**Comment by eneelo** [comment]
> I like that one better than the old. I will spin it up tomorrow morning and look more closely🤓

I have now enabled Furo as a theme. Screenshots are included in PR description above. To test it and get a 'hands-on' feeling:

1. Install Furo, `python -m pip install furo`
2. In `docs/source/conf.py`, set `THEME = 'furo'`
3. Compile docs, `sphinx-build -a -E -b html docs\source docs\_build`

Personally, I like both `sphinx_rtd_theme` and the `furo` theme, but I might be slightly in favor of Furo. It has a simple yet likable appearance, and I like the split into a main TOC on the left-hand-side and a scrollable page-specific TOC on the right-hand-side. To get a sense on how Furo works on a mobile device, visit https://devguide.python.org/ from your phone.

In any case, both themes seem to work very well and appear as better options than the existing theme.

**Comment by tovop** [comment]
Nice work @eneelo. I'm in favor of the Furo theme. I like  the cleaner look and think it works on mobile also. No warnings at all when I clone and build.

**Comment by tovop** [comment]
I'll review as soon as you complete the final two tasks.

**Comment by eneelo** [comment]
> Nice work @eneelo. I'm in favor of the Furo theme. I like the cleaner look and think it works on mobile also. No warnings at all when I clone and build.

Thanks ☺️ 
And it's decided then, let's go for Furo. Will update accordingly then mark as read for review.

**Review by tovop — APPROVED** [review]
A real upgrade. Looks nice.

**Pull request merged**
